-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 00:17:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Dados
-- -----------------------------------------------------
-- Esquema para dados SqlServer

-- -----------------------------------------------------
-- Schema Dados
--
-- Esquema para dados SqlServer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Dados` DEFAULT CHARACTER SET utf8 ;
USE `Dados` ;

-- -----------------------------------------------------
-- Table `Dados`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dados`.`cidade` (
  `idIbge` INT NOT NULL AUTO_INCREMENT,
  `uf` VARCHAR(2) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIbge`),
  UNIQUE INDEX `idIbge_UNIQUE` (`idIbge` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dados`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dados`.`veiculo` (
  `idveiculo` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `placa` VARCHAR(8) NULL,
  `disponibilidade` CHAR(1) NOT NULL DEFAULT 'S',
  `ano` YEAR NULL,
  `idIbge` INT NOT NULL,
  PRIMARY KEY (`idveiculo`, `idIbge`),
  UNIQUE INDEX `idveiculo_UNIQUE` (`idveiculo` ASC),
  INDEX `fk_veiculo_cidade1_idx` (`idIbge` ASC),
  CONSTRAINT `fk_veiculo_cidade1`
    FOREIGN KEY (`idIbge`)
    REFERENCES `Dados`.`cidade` (`idIbge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dados`.`Motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dados`.`Motorista` (
  `idMotorista` INT NOT NULL AUTO_INCREMENT,
  `codMotorista` VARCHAR(45) NOT NULL,
  `idveiculo` INT NOT NULL,
  PRIMARY KEY (`idMotorista`, `idveiculo`),
  UNIQUE INDEX `idMotorista_UNIQUE` (`idMotorista` ASC),
  INDEX `fk_Motorista_veiculo1_idx` (`idveiculo` ASC),
  CONSTRAINT `fk_Motorista_veiculo1`
    FOREIGN KEY (`idveiculo`)
    REFERENCES `Dados`.`veiculo` (`idveiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dados`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dados`.`endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `cep` VARCHAR(10) NOT NULL,
  `idIbge` INT NOT NULL,
  PRIMARY KEY (`idEndereco`, `idIbge`),
  UNIQUE INDEX `idEndereco_UNIQUE` (`idEndereco` ASC),
  INDEX `fk_endereco_cidade1_idx` (`idIbge` ASC),
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`idIbge`)
    REFERENCES `Dados`.`cidade` (`idIbge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dados`.`cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dados`.`cadastro` (
  `idcadastro` INT NOT NULL AUTO_INCREMENT,
  `nomeCompleto` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `dataInclusao` DATE NOT NULL,
  `dataAlteracao` DATE NULL,
  `dataExclusao` DATE NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(15) NULL,
  `ativo` CHAR(1) NOT NULL DEFAULT 'S',
  `idMotorista` INT NOT NULL,
  `idEndereco` INT NOT NULL,
  PRIMARY KEY (`idcadastro`, `idMotorista`, `idEndereco`),
  UNIQUE INDEX `idcadastro_UNIQUE` (`idcadastro` ASC),
  INDEX `fk_cadastro_Motorista1_idx` (`idMotorista` ASC),
  INDEX `fk_cadastro_endereco1_idx` (`idEndereco` ASC),
  CONSTRAINT `fk_cadastro_Motorista1`
    FOREIGN KEY (`idMotorista`)
    REFERENCES `Dados`.`Motorista` (`idMotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cadastro_endereco1`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `Dados`.`endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dados`.`pFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dados`.`pFisica` (
  `idpFisica` INT NOT NULL AUTO_INCREMENT,
  `dataNascimento` DATE NULL,
  `genero` ENUM('M', 'F', 'O') NULL,
  `idcadastro` INT NOT NULL,
  PRIMARY KEY (`idpFisica`, `idcadastro`),
  UNIQUE INDEX `idpFisica_UNIQUE` (`idpFisica` ASC),
  INDEX `fk_pFisica_cadastro1_idx` (`idcadastro` ASC),
  CONSTRAINT `fk_pFisica_cadastro1`
    FOREIGN KEY (`idcadastro`)
    REFERENCES `Dados`.`cadastro` (`idcadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dados`.`pJuridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dados`.`pJuridica` (
  `idpJuridica` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) NOT NULL,
  `insEstadual` VARCHAR(45) NULL,
  `idcadastro` INT NOT NULL,
  PRIMARY KEY (`idpJuridica`, `idcadastro`),
  UNIQUE INDEX `idpJuridica_UNIQUE` (`idpJuridica` ASC),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  INDEX `fk_pJuridica_cadastro1_idx` (`idcadastro` ASC),
  CONSTRAINT `fk_pJuridica_cadastro1`
    FOREIGN KEY (`idcadastro`)
    REFERENCES `Dados`.`cadastro` (`idcadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dados`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dados`.`servico` (
  `idservico` INT NOT NULL AUTO_INCREMENT,
  `dataInicio` DATETIME NOT NULL,
  `dataAlteracao` DATETIME NULL,
  `dataFinal` DATETIME NULL,
  `dataPagamento` DATETIME NULL,
  `empresaSolicitante` VARCHAR(45) NULL,
  `passageiro` VARCHAR(45) NULL,
  `endBase` VARCHAR(45) NULL,
  `endOrigem` VARCHAR(45) NULL,
  `endDestino` VARCHAR(45) NULL,
  `kmPercorrida` INT NULL,
  `valorPedagio` DECIMAL(2) NULL,
  `valorCobrado` DECIMAL(2) NULL,
  `numOS` VARCHAR(20) NULL,
  `observacoes` LONGTEXT NULL,
  `nfeServicoMotorista` INT NULL,
  `valorTotal` DECIMAL(2) NULL,
  `statusPagamento` ENUM('Pendente', 'Realizado', 'Finalizado') NULL DEFAULT 'Pendente',
  `acrescimo` DECIMAL(2) NULL,
  `desconto` DECIMAL(2) NULL,
  `idveiculo` INT NOT NULL,
  `idMotorista` INT NOT NULL,
  PRIMARY KEY (`idservico`, `idveiculo`, `idMotorista`),
  UNIQUE INDEX `idservico_UNIQUE` (`idservico` ASC),
  INDEX `fk_servico_veiculo1_idx` (`idveiculo` ASC),
  INDEX `fk_servico_Motorista1_idx` (`idMotorista` ASC),
  CONSTRAINT `fk_servico_veiculo1`
    FOREIGN KEY (`idveiculo`)
    REFERENCES `Dados`.`veiculo` (`idveiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servico_Motorista1`
    FOREIGN KEY (`idMotorista`)
    REFERENCES `Dados`.`Motorista` (`idMotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
